name = "prescio"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Custom domains (requires zone to be active in Cloudflare)
routes = [
  { pattern = "prescio.fun", custom_domain = true },
  { pattern = "app.prescio.fun", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
API_BACKEND = "https://airfare-knock-bright-licenses.trycloudflare.com"
